---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ContentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-pict-web
      WebsiteConfiguration:
        IndexDocument: "index.html"

  ContentsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentsBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${ContentsBucket}/*
            Principal: "*"

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Schema:
        - Name: 'email'
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 2048
          Required: true
          AttributeDataType: String
          Mutable: true
      AliasAttributes: [ 'email' ]
      AutoVerifiedAttributes: [ 'email' ]
      EmailVerificationSubject: 'Your verification code'
      EmailVerificationMessage: 'Your confirmation code is {####}.'
      MfaConfiguration: 'OFF'
      UserPoolName: !Ref AWS::StackName
      Policies:
        PasswordPolicy:
          RequireLowercase: false
          RequireSymbols: false
          RequireNumbers: false
          MinimumLength: 6
          RequireUppercase: false

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: 'pict-app'
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool

Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient


