---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ContentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-pict-web
      WebsiteConfiguration:
        IndexDocument: "index.html"

  ContentsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentsBucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${ContentsBucket}/*
            Principal: "*"
